### ISSUE TITLE
add way to easily make new pages

### ISSUE THREAD

**Issue by roberbob** [flancast90/Minus#3]
hi,
Is there a way to add new pages or slides to this tool?

I would like to make a slide to show websites made for clients

thank

**Comment by flancast90** [comment]
Hi @roberbob,

This feature is on the roadmap for the next major version bump! 
You can see proposed changes at https://github.com/flancast90/Minus#todo.

For now, you can change the code within ``index.html``. The syntax for adding slides is shown there.
